name: Build and Publish NuGet Package

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore StrongResult
        run: dotnet restore StrongResult/StrongResult.csproj

      - name: Restore StrongResult.Test
        run: dotnet restore StrongResult.Test/StrongResult.Test.csproj

      - name: Build StrongResult
        run: dotnet build StrongResult/StrongResult.csproj --configuration Release --no-restore

      - name: Build StrongResult.Test
        run: dotnet build StrongResult.Test/StrongResult.Test.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test StrongResult.Test/StrongResult.Test.csproj --configuration Release --no-build --verbosity normal

      - name: Copy README to project folder
        run: cp README.md StrongResult/README.md

      - name: Get tag for current commit
        id: git_tag
        run: |
          TAG=$(git tag --points-at HEAD | head -n 1)
          if [ -z "$TAG" ]; then
            echo "tag=" >> $GITHUB_OUTPUT
          else
            echo "tag=${TAG#v}" >> $GITHUB_OUTPUT
          fi
          echo "TAG=${TAG}" # For debug

      - name: Get latest NuGet version
        id: nuget_version
        run: |
          PACKAGE_ID="StrongResult"
          RESPONSE=$(curl -s "https://api.nuget.org/v3-flatcontainer/$PACKAGE_ID/index.json")
          echo "NuGet API response: $RESPONSE"
          VERSIONS=$(echo "$RESPONSE" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
          LATEST_VERSION=$(echo "$VERSIONS" | tail -1)
          if [ -z "$LATEST_VERSION" ]; then
            LATEST_VERSION="0.1.0"
          fi
          echo "::set-output name=nuget_versions::$VERSIONS"
          echo "::set-output name=nuget_latest::$LATEST_VERSION"

      - name: Calculate next version
        id: version
        run: |
          TAG="${{ steps.git_tag.outputs.tag }}"
          NUGET_VERSIONS="${{ steps.nuget_version.outputs.nuget_versions }}"
          NUGET_LATEST="${{ steps.nuget_version.outputs.nuget_latest }}"
          if [ "$TAG" != "" ] && ! echo "$NUGET_VERSIONS" | grep -qx "$TAG"; then
            NEW_VERSION="$TAG"
          else
            VERSION="$NUGET_LATEST"
            IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
            PATCH=$((PATCH+1))
            NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          fi
          echo "Next version: $NEW_VERSION"
          echo "::set-output name=version::$NEW_VERSION"

      - name: Pack
        run: dotnet pack StrongResult/StrongResult.csproj --configuration Release --no-build --output ./nupkg /p:PackageVersion=${{ steps.version.outputs.version }}

      - name: Publish to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
